config/routes.rb
Kuikui::Application.routes.draw do
  resources :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @message = Message.new
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Kuikui</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Kuikui</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span9">
            <%= yield %>
          </div>
          <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                    <li><%= link_to "Link1", "/path1"  %></li>
                    <li><%= link_to "Link2", "/path2"  %></li>
                    <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div>
            </div>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer class="container">
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="clearfix">
    <div class="input">
      <%= f.text_area :content, :class => 'text_area span6', :rows => 5 %>
    </div>
    <br/>
    <button class="btn btn-primary" type="submit">Save</button>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<h1>What's happening ?</h1>
<br/>
<%= render :partial => 'form' %>

<% @messages.each do |message| %>
  <div class="row message">
    <div class="span1 photo">
      <%= image_tag "http://www.gravatar.com/avatar/ee8ea294c76022c5a6e163a05d255700.png" %>
    </div>
    <div class="span5">
      <div class="row">
        <div class="span4">
          <strong>
            Apirak
          </strong>
          <%= time_ago_in_words(message.created_at) %>
        </div>
        <div class="span1">
          <%= link_to raw("<i class='icon-pencil'></i>"), edit_message_path(message) %>
          <%= link_to raw("<i class='icon-trash'></i>"), message_path(message), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
        </div>
      </div>
      <div class="row">
        <div class="span5">
          <%= link_to message.content, message_path(message) %>
        </div>
      </div>
      <div class="row">
        <div class="span5">
          #abc, #bca
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= render :partial => 'form' %>

app/views/messages/show.html.erb
<h1>Message</h1>

<p>
  <b>Content</b><br>
  <%= @message.content %>
</p>

<p>
  <b>Tags</b><br>
  <%= @message.tags %>
</p>

<div class="form-actions">
  <%= link_to 'Back', messages_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_message_path(@message), :class => 'btn' %>
  <%= link_to 'Delete', message_path(@message), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>